name: build and push Docker

on:
  push:
    branches: [main, freature/actividad2]
jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: saludo
        run: echo "Hola mundo" 